import collections,datetime,hashlib,html,json
from pathlib import Path
B=Path(__file__).resolve().parent;R=B.parents[3];sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ctx=json.loads((B/'audit-context.json').read_text());py=json.loads((B/'backend-coverage.json').read_text());js=json.loads((B/'frontend-coverage.json').read_text())
assert ctx['source_unchanged'] and ctx['source_hashes']=={f:sha(R/f) for f in ctx['source_hashes']}
assert list(py['files'])==['app/server.py'];pt=py['totals'];source=(R/'web/app.js').read_text().splitlines();why={61:'登录错误反馈的DOM节点缺失备用出口；正常渲染始终创建#login-error。',92:'renderShell缺user早返回；可操作入口及异步收尾均先检查身份。',106:'pageContent未知page备用出口；界面导航只提供四个固定page。',110:'heading省略aside的默认参数；当前四个调用均显式提供参数。',118:'北京时间Intl日期文字不包含“日”时的空星期备用；目标Chromium实际中文Intl返回规范日期。'}
missing=[]
for x in js['missing_branches']:
 line=x['condition']['start']['line'];missing.append({**x,'file':'web/app.js','source_line':line,'source':source[line-1],'classification':'defensive_or_unreachable_in_confirmed_native_scope','tester_recommendation':'无需新增正式场景；保留分母及未覆盖事实，等待独立审阅确认。','reason':why[line]})
inventory={'revision':ctx['revision'],'source_hashes':ctx['source_hashes'],'backend_missing_lines':py['files']['app/server.py']['missing_lines'],'backend_missing_branches':py['files']['app/server.py']['missing_branches'],'frontend_uncovered_lines':js['uncovered_lines'],'frontend_missing_statements':js['missing_statements'],'frontend_missing_functions':js['missing_functions'],'frontend_missing_branches':missing,'independent_review':'pending'}
(B/'uncovered-inventory.json').write_text(json.dumps(inventory,ensure_ascii=False,indent=2)+'\n')
race=json.loads((B/'change-role-identity-race-results.json').read_text());
guards=json.loads((B/'pending-guard-results.json').read_text());assert len(guards['results'])==6 and all(x['status']=='passed' for x in guards['results']);static=json.loads((B/'static-unsupported-control.json').read_text());assert static['passed']
corrections=[]
for f in ['harness-wait-corrections.json','runtime-dependency-correction.json','startup-coverage-adaptation.json']:corrections.append({'file':f,**json.loads((B/f).read_text())})
summary={'revision':ctx['revision'],'generated_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_hashes':ctx['source_hashes'],'backend':{'file':'app/server.py','tool':'coverage.py 7.16.2','lines':{'covered':pt['covered_lines'],'total':pt['num_statements'],'percent':round(100*pt['covered_lines']/pt['num_statements'],2)},'branches':{'covered':pt['covered_branches'],'total':pt['num_branches'],'percent':round(100*pt['covered_branches']/pt['num_branches'],2)},'excluded_lines':pt['excluded_lines']},'frontend':{'file':'web/app.js','tool':'Istanbul instrumenter 6.0.3','lines':js['summary']['lines'],'branches':js['summary']['branches'],'functions':js['summary']['functions'],'statements':js['summary']['statements'],'skipped':0},'scope':'固定stage10新源码的全部现有可执行测试harness、7条标准unittest、stage09补测矩阵及旧补充探针；计数只用本目录的新数据，不合并旧源码counter。HTML/CSS不属于执行语句分母，空app/__init__.py无执行行。','fresh_counter_policy':'fresh-directory only; canonicalize exact matching server source copies; Istanbul maps match current static map; per-process max and cross-process presence union within same source revision','job_count':len(ctx['jobs']),'jobs':ctx['jobs'],'product_findings':[{'family':'changeRole_late_session200_cross_identity','status':'confirmed_real_failure','items':2,'evidence':'change-role-identity-race-results.json','impact':'后台新会话有效，UI却恢复旧账号、团队、角色与菜单并显示旧成功提示，后续新会话数据被旧身份标记。'}],'followup_jobs':[{'job':'pending-guards','items':6,'status':'passed','evidence':'pending-guard-results.json'},{'job':'static-control','items':9,'status':'passed','scope':'non-API compatibility diagnostic','evidence':'static-unsupported-control.json'}],'harness_corrections':corrections,'scenario_design_followup':{'new_ids_added_by_this_audit':0,'formal_ledgers_modified':False,'refinements_to_existing_methods_recommended':['AI-WB-ui-load-token-races: pending-session stale与同token但!user的两条实际独立路径','AI-WB-ui-self-demotion-session-failure: pending重试自身真实401/503/网络和再次恢复','AI-WB-ui-role-demotion-reload: 非self提交、身份查询故障后真实admin重试恢复'],'new_source_guard_items_executed':6,'late_identity_state_combination_matrix':race,'required_additional_existing_method_refinement':'changeRole本身旧session实际200跨logout/new-login到达必须不覆盖新身份；自身/他人PATCH两项真实失败，须纳入既有AI-WB-ui-role-demotion-reload / AI-WB-ui-load-token-races独立复审。','independent_review':'pending; formal Analyst/Reviewer to incorporate and independently judge sufficiency'},'acceptance_conclusion':'coverage_is_not_acceptance; 本审计未写正式run，不宣称全部167场景通过。所有旧失败及原harness同步错误尝试保留，完整验收以独立Playbook新run及Review为准。','remaining_uncovered':{'backend_lines':0,'backend_branch_paths':0,'frontend_lines':1,'frontend_statement_paths':2,'frontend_branch_paths':5,'frontend_function_paths':0,'inventory':'uncovered-inventory.json','additional_mandatory_scenarios_for_five_defensive_exits_recommended':0,'required_additional_identity_state_matrix_refinements':1,'independent_review':'pending'}}
(B/'summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n')
(B/'README.md').write_text(f'''# Stage10 新源码覆盖率审计\n\n固定版本 `{ctx['revision']}`。后端行 **389/389（100%）**、分支 **126/126（100%）**；前端行 **197/198（99.49%）**、分支 **187/192（97.39%）**、函数 **86/86（100%）**、语句 **343/345（99.42%）**。无行/分支排除，全部分母保留。\n\n本目录只使用当前源码新产生的计数，旧目录仅提供 coverage.py 与 Istanbul 工具。`backend-source-verification.json`核对所有现存隔离server.py的SHA并将同源码位置归一；`frontend-static-map.json`直接从当前app.js产生，所有JS输入在合并前校验映射一致（仅统一JS undefined/null序列化差异）。\n\n30项原harness重跑包括7条unittest、完整旧API/runtime/UI最终脚本、stage09 API/identity/dialog矩阵与旧full_api_matrix和独立covered probes；12项UI续脚本在单个全新进度中顺序执行，不seed旧passed。`audit-context.json`保存每次进程退出事实；退出0不等于完整方法通过。\n\n新增 `pending_identity_guards.py` 真实执行6条新代码路径：pending旧200遇stale token；token未变但早期真实401清user后阻止旧200复活；非self修改后恢复admin；pending重试真实401、503、网络及再次恢复。故障仅在浏览器网络边界，实际角色PATCH、会话HTTP撤销、route.fetch的200/401、loadToken、DOM和后续请求均保留。6项全部断言通过，正式设计应在既有方法独立细化与审阅，不新增平行业务需求。\n\n`static_unsupported_control.py`另实测9项非API静态unsupported方法继承拒绝，仅兼容诊断，不冒充正式API新增场景；API的60项unsupported矩阵仍独立要求JSON。\n\n初始两条UI断言在state先更新而DOM未完成、上一轮toast仍非空时过早检查。严格增加最终DOM/按钮恢复等待后独立两组业务断言完成；保留初始失败JSON/截图与纠正副本。runtime_edges依赖本轮runtime_complete真正创建的process-persist.sqlite，已按真实依赖顺序再执行；初始缺前置库日志保留。CLI覆盖率变体使用port0及localhost保护用户demo并启用计数，Mac无127.0.0.2别名及stdout读取适配失败尝试保留；实际默认8766/不同loopback/Python311以正式Docker矩阵证明。\n\n剩余5条前端出口在`uncovered-inventory.json`逐位置说明，属于当前原生界面未触发的防御备用；计数保留。Tester在6条新guard路径实测后未提出额外必要场景，须由独立Reviewer确认。\n\n覆盖率与逐场景验收证据不是同义。本审计没有修改正式ledger或run，不能据此声称全部167场景通过或允许发布。正式结论以当前Playbook单一新run、证据审阅与最终gate为准。\n\n补充状态组合实测发现真实产品失败：changeRole本身的/session实际200跨原生logout和新登录延迟到达时，旧user覆盖新身份。自身降权→跨团队other、他人晋升→同团队bob成员两项均失败；实际后台新session始终正确，UI账号、团队/权限菜单却被旧身份改写并出现旧成功toast。参见`change-role-identity-race-results.json`及逐项HTTP/DOM/截图。这说明分支覆盖完成仍可能缺重要状态组合；须细化既有角色修改/身份竞态方法、修复产品后建立新源码新运行。本版本不批准发布。\n''')
rows=''.join(f'<tr><td>{x["source_line"]}</td><td>{html.escape(x["type"])}</td><td>{html.escape(x["reason"])}</td></tr>' for x in missing)
(B/'index.html').write_text(f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>Stage10 fresh coverage</title><style>body{{font:16px/1.6 system-ui;max-width:1080px;margin:48px auto;padding:0 24px;color:#172535;background:#f5f7fb}}table{{border-collapse:collapse;background:white;width:100%}}td,th{{padding:12px;border:1px solid #dfe5ed;text-align:left}}code{{font-size:13px}}a{{color:#1564b5}}</style><h1>Stage10 新源码覆盖率</h1><p>版本 <code>{ctx['revision']}</code> · 全新计数 · 不合并旧源码 · 完整验收另见正式新 run</p><table><tr><th>源码</th><th>行</th><th>分支</th><th>函数</th></tr><tr><td>app/server.py</td><td>389/389 · 100%</td><td>126/126 · 100%</td><td>—</td></tr><tr><td>web/app.js</td><td>197/198 · 99.49%</td><td>187/192 · 97.39%</td><td>86/86 · 100%</td></tr></table><p><a href="html/backend/index.html">后端源码覆盖率</a> · <a href="frontend-coverage.json">前端原始计数</a> · <a href="summary.json">完整摘要与运行记录</a> · <a href="pending-guard-results.json">新身份守卫6项实测</a></p><h2>保留的5条前端未覆盖出口</h2><table><tr><th>行</th><th>类型</th><th>说明（待独立审阅）</th></tr>{rows}</table><h2>实际产品失败</h2><p><a href="change-role-identity-race-results.json">角色修改旧session200跨logout/new-login：两项失败</a>。后台新会话正确，UI旧身份覆盖新身份，本版本不批准发布。</p><p>覆盖率不等于167场景验收通过。没有修改正式台账，也没有批准发布。</p></html>''')
manifest_files=['summary.json','README.md','uncovered-inventory.json','backend-coverage.json','backend-source-verification.json','frontend-coverage.json','frontend-static-map.json','frontend-source-map.json','audit-context.json','pending-guard-results.json','static-unsupported-control.json','change-role-identity-race-results.json']
(B/'report-integrity.json').write_text(json.dumps({'revision':ctx['revision'],'sha256':{f:sha(B/f) for f in manifest_files},'source_unchanged':True,'old_counter_data_merged':False},ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'backend':summary['backend'],'frontend':summary['frontend'],'jobs':len(ctx['jobs'])},ensure_ascii=False))
