import run_ui_acceptance as b
from run_ui_acceptance import *
def rejects(e,o):
 e.login('admin');p=e.page;bid=create(e,day='2030-04-10');e.nav('bookings');p.locator(f'[data-cancel="{bid}"]').click();before=e.snap();old=b.FIX;b.FIX=real_dt.fromisoformat('2030-04-10T10:00:00+08:00');p.locator('#confirm-cancel').click();p.wait_for_function('() => document.querySelector("#confirm-error").textContent.length>0');assert '已经开始' in p.locator('#confirm-error').inner_text();assert not p.locator('#confirm-cancel').is_disabled();assert e.snap()==before;o['real_cancel_rejection']={'clock':b.FIX.isoformat(),'error':p.locator('#confirm-error').inner_text(),'unchanged':True,'shot':e.shot('cancel-business409')};b.FIX=old;p.locator('#confirm-cancel').click();p.locator('#confirm-dialog').wait_for(state='hidden');p.wait_for_function('() => !state.loading');assert next(x for x in e.api('/bookings')[1]['bookings'] if x['id']==bid)['status']=='cancelled';e.nav('manage');rooms=e.api('/rooms')[1]['rooms'];p.locator(f'[data-edit-room="{rooms[0]["id"]}"]').click();f=p.locator('#room-form');f.locator('[name=name]').fill(rooms[1]['name']);f.locator('[name=location]').fill('业务拒绝保留');before=e.snap();f.locator('[type=submit]').click();p.wait_for_function('() => document.querySelector("#room-error").textContent.length>0');assert e.snap()==before;assert f.locator('[name=location]').input_value()=='业务拒绝保留';o['edit_real_conflict']=p.locator('#room-error').inner_text();f.locator('[name=name]').fill('修改后合法');f.locator('[type=submit]').click();p.locator('#room-dialog').wait_for(state='hidden');p.wait_for_function('() => !state.loading');assert any(x['name']=='修改后合法' for x in e.api('/rooms')[1]['rooms'])
if __name__=='__main__':
 data=json.load(open(RUN/'ui-results.json'));b.results={r['method_id']:{k:v for k,v in r.items() if k!='method_id'} for r in data['method_results']};b.groups=json.load(open(E/'progress.json'))['groups'];b.serial=930
 for mid in ['AI-interface-experience-7','AI-interface-experience-9','AI-WB-ui-submit-button-matrix']:
  b.results[mid]['status']='unproven';b.results[mid]['actual']='921准备把服务推进49小时，先触发会话过期而非目标409；保留证据，现使用当日预约推进一小时重跑。'
 with sync_playwright() as pw:
  b.browser=pw.chromium.launch(headless=True);group('real-cancel-edit-business-rejections',['AI-interface-experience-7','AI-interface-experience-9','AI-WB-ui-submit-button-matrix'],rejects);b.browser.close()
